site_name: "Telerobotic Platform: Remote control of a humanoid robot"

# site_url: http://127.0.0.1:8000/
site_url: https://hugoperez3i.github.io/RemoteControlHumanoidRobot/

nav:
  - Home:
    - index.md
  - Application Protocol: 
    - Application Protocol/Protocol Definition.md
    - Application Protocol/Control Query.md
    - Application Protocol/Identification Query.md
    - Application Protocol/Robot Selection.md
    - Application Protocol/Servo Movement.md
    - Application Protocol/MCU Information.md
    - Application Protocol/Execution Mode.md
    - Application Protocol/Move All Query.md
    - Application Protocol/Upload Information.md
    - Application Protocol/Server Shutdown.md
  - Demo: 
    - demos/Demo Showcase.md
    - demos/Platform Showcase.md
    - demos/UE5 Module Showcase.md

theme:
  name: material
  logo: assets/Logo.png
  favicon: assets/Logo.png
  font: false
  font:
    text: Noto Sans
    code: Times New Romans
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: brown
      accent: deep-orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: brown
      accent: deep-orange
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tabs
    - content.tabs.link
    - toc.follow
    - toc.integrate
    - navigation.top
plugins:
  - search
  - privacy
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - attr_list
  - md_in_html
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hugoperez3i/RemoteControlHumanoidRobot
