site_name: "Telerobotic Platform: Remote control of a humanoid robot"

site_url: http://127.0.0.1:8000/
# site_url: https://hugoperez3i.github.io/RemoteControlHumanoidRobot/
theme:
  name: material
  logo: assets/Logo.png
  favicon: assets/Logo.png
  font: false
  font:
    text: Noto Sans
    code: Times New Romans
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: brown
      accent: deep-orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: brown
      accent: deep-orange
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tabs
    - toc.follow
    - toc.integrate
    - navigation.prune
    - navigation.top
plugins:
  - search
  - privacy
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hugoperez3i/RemoteControlHumanoidRobot
